apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
  namespace: msc-de1-project
  labels:
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/part-of: msc-de1-project
data:
  APP_ENV: "kubernetes"
  TZ: "UTC"
  # Options gunicorn additionnelles (lues nativement par gunicorn)
  GUNICORN_CMD_ARGS: "--timeout 30 --graceful-timeout 20"
